### ISSUE TITLE
[BUG]: GatherMate2 does not rotate nodes when combined with FarmHud

### ISSUE THREAD

**Issue by gabriel-oana** [HizurosWoWAddOns/FarmHud#5]
### WoW client

WoW Retail

### What happened?

**Bug report:**
The nodes shown by GatherMate2 addon do not rotate with the rest of the elements when FarmHud is activated.
The first image shows a "herb" node (green circle) aligned to the actual icon of the herb. 
The second image shows the "herb" node (green circle) not aligned to the icon of the herb due to player rotating camera. 
This issue seems to have appeared since the last client update of the game. 

![image](https://user-images.githubusercontent.com/25056530/198884707-36a60c4c-62bb-443a-a2cd-98348556143a.png)
![image](https://user-images.githubusercontent.com/25056530/198884721-dd886723-6736-4fd8-8567-d5772b9858b7.png)

** How to replicate **

- Install GatherMate2 addon and import mining / herb data.
- Rotate the camera and fly to see that nodes always move in a direction from N-S regardless of the direction of movement of the player.

**What I have tried**

- Disabled all addons apart from FarmHud and GatherMate2
- Reinstalled both addons. 

### Other addons?

GatherMate2
GatherMate2Data
Routes
Farmhud [QuestArrow]
Farmhud [TrailPath]

**Comment by Beardedrasta** [comment]
I found a fix for this not sure if you still needed it or not, in order for the addon to rotate correctly, You have to go into Edit Mode in game and right click the minimap and turn on rotate, then open up FarmHud options and tick the "Rotate" option there as well in the general tab. After both options are enabled then it will correctly display. :) Hope i wasn't to late.

**Comment by gabriel-oana** [comment]
You are a genius. That has fixed the issue indeed. I didn't even realise one could right click on the map in edit mode. 
I think this issue can now be closed?

**Comment by Beardedrasta** [comment]
Yeah the issue can be closed now, I've heard word that the creator of the addon is releasing an official fix for the interface issue, But for now I'm glad i figured that out atleast, I saw a TON of people asking about it on the curseforge page, and a few on here. so shared what i had found. Have fun on your collections!!

**Comment by gabriel-oana** [comment]
That is perfect. 
Again, thank you and the team for making this AddOn. It is great. I have been using it for a long time and now made significantly more gold using it. 
I'll close the ticket now :)
